version: '3'
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: itsource_27
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: 